// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2s5uoemv_PlYEdbZ0nlNA8_JLwZjQVfQ',
    appId: '1:197923465017:web:79c082021681fa0eb86ae8',
    messagingSenderId: '197923465017',
    projectId: 'quoteapp-nkdev',
    authDomain: 'quoteapp-nkdev.firebaseapp.com',
    databaseURL: 'https://quoteapp-nkdev-default-rtdb.firebaseio.com',
    storageBucket: 'quoteapp-nkdev.appspot.com',
    measurementId: 'G-NQ3NJ743PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhS2PCjZDz7jBNarEtPXvzy_htm0RNkEw',
    appId: '1:197923465017:android:3077fa6abc65623bb86ae8',
    messagingSenderId: '197923465017',
    projectId: 'quoteapp-nkdev',
    databaseURL: 'https://quoteapp-nkdev-default-rtdb.firebaseio.com',
    storageBucket: 'quoteapp-nkdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYHwozfxo7CszW1jqrltc3Jtp_vIlS7SA',
    appId: '1:197923465017:ios:c8459f562d269b16b86ae8',
    messagingSenderId: '197923465017',
    projectId: 'quoteapp-nkdev',
    databaseURL: 'https://quoteapp-nkdev-default-rtdb.firebaseio.com',
    storageBucket: 'quoteapp-nkdev.appspot.com',
    androidClientId: '197923465017-2tmuorp6s7tllaallrv6k95mvjuqklvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.quoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYHwozfxo7CszW1jqrltc3Jtp_vIlS7SA',
    appId: '1:197923465017:ios:c8459f562d269b16b86ae8',
    messagingSenderId: '197923465017',
    projectId: 'quoteapp-nkdev',
    databaseURL: 'https://quoteapp-nkdev-default-rtdb.firebaseio.com',
    storageBucket: 'quoteapp-nkdev.appspot.com',
    androidClientId: '197923465017-2tmuorp6s7tllaallrv6k95mvjuqklvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.quoteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2s5uoemv_PlYEdbZ0nlNA8_JLwZjQVfQ',
    appId: '1:197923465017:web:6ade3db4f81410edb86ae8',
    messagingSenderId: '197923465017',
    projectId: 'quoteapp-nkdev',
    authDomain: 'quoteapp-nkdev.firebaseapp.com',
    databaseURL: 'https://quoteapp-nkdev-default-rtdb.firebaseio.com',
    storageBucket: 'quoteapp-nkdev.appspot.com',
    measurementId: 'G-SJH1F9F939',
  );

}